{*
 * @version    $Id: template.phtml 2 2009-07-13 20:58:52Z david@grudl.com $
 * @param Paginator $paginator
 * @param array     $steps
 *
 * upraveno pro twitter bootstrap by @3knedle
 *}

{if $paginator->pageCount > 1}
<div class="pagination pagination-centered">
    <ul>
	{if $paginator->isFirst()}
	<li class="disabled"><a>« Previous</a></li>
	{else}
	<li><a href="{link this, 'page' => $paginator->page - 1}" rel="prev">« Previous</a><li>
	{/if}

	{foreach $steps as $step}
	{if $step == $paginator->page}
		<li class="active"><a href="#">{$step}</a></li>
	{else}
		<li><a href="{link this, 'page' => $step}">{$step}</a></li>
	{/if}
	{if $iterator->nextValue > $step + 1}<li class="disabled"><a>…</a></li>{/if}
	{/foreach}

	{if $paginator->isLast()}
            <li class="disabled"><a >Next »</a></li>
	{else}
            <li><a href="{link this, 'page' => $paginator->page + 1}" rel="next">Next »</a></li>
	{/if}
    </ul>        
</div>
{/if}
